<?php

namespace Database\Seeders;

use App\Models\Continent;
use App\Models\Country;
use App\Models\Status;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $countries = [
            [
                "name" => "Afghanistan",
                "slug" => "afghanistan",
                "code" => "AFG",
                "dial_code" => "+93",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Africa",
                "slug" => "africa",
                "code" => "AFR",
                "dial_code" => null,
                "flag" => null,
                "continent" => "World",
            ],
            [
                "name" => "Albania",
                "slug" => "albania",
                "code" => "ALB",
                "dial_code" => "+355",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Algeria",
                "slug" => "algeria",
                "code" => "ALG",
                "dial_code" => "+213",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "American Samoa",
                "slug" => "american-samoa",
                "code" => "ASM",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Oceania",
            ],
            [
                "name" => "Andorra",
                "slug" => "andorra",
                "code" => "AND",
                "dial_code" => "+376",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Angola",
                "slug" => "angola",
                "code" => "ANG",
                "dial_code" => "+244",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Anguilla",
                "slug" => "anguilla",
                "code" => "AIA",
                "dial_code" => "+1-264",
                "flag" => null,
                "continent" => "N/C America",
            ],
            [
                "name" => "Antigua and Barbuda",
                "slug" => "antigua-and-barbuda",
                "code" => "ATG",
                "dial_code" => "+1-268",
                "flag" => null,
                "continent" => "N/C America",
            ],
            [
                "name" => "Arameans Suryoye",
                "slug" => "arameans-suryoye",
                "code" => "ARS",
                "dial_code" => null,
                "flag" => null,
                "continent" => "World",
            ],
            [
                "name" => "Argentina",
                "slug" => "argentina",
                "code" => "ARG",
                "dial_code" => "+54",
                "flag" => "https://logos.football-data.org/762.png",
                "continent" => "South America",
            ],
            [
                "name" => "Armenia",
                "slug" => "armenia",
                "code" => "ARM",
                "dial_code" => "+374",
                "flag" => "https://logos.football-data.org/1970.svg",
                "continent" => "Europe",
            ],
            [
                "name" => "Aruba",
                "slug" => "aruba",
                "code" => "ABW",
                "dial_code" => "+297",
                "flag" => null,
                "continent" => "N/C America",
            ],
            [
                "name" => "Asia",
                "slug" => "asia",
                "code" => "ASI",
                "dial_code" => null,
                "flag" => null,
                "continent" => "World",
            ],
            [
                "name" => "Australia",
                "slug" => "australia",
                "code" => "AUS",
                "dial_code" => "+61",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Austria",
                "slug" => "austria",
                "code" => "AUT",
                "dial_code" => "+43",
                "flag" => "https://logos.football-data.org/816.svg",
                "continent" => "Europe",
            ],
            [
                "name" => "Azerbaijan",
                "slug" => "azerbaijan",
                "code" => "AZE",
                "dial_code" => "+994",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Bahamas",
                "slug" => "bahamas",
                "code" => "BHS",
                "dial_code" => "+1-242",
                "flag" => null,
                "continent" => "N/C America",
            ],
            [
                "name" => "Bahrain",
                "slug" => "bahrain",
                "code" => "BHR",
                "dial_code" => "+973",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Bangladesh",
                "slug" => "bangladesh",
                "code" => "BAN",
                "dial_code" => "+880",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Barbados",
                "slug" => "barbados",
                "code" => "BRB",
                "dial_code" => "+1-246",
                "flag" => null,
                "continent" => "N/C America",
            ],
            [
                "name" => "Belarus",
                "slug" => "belarus",
                "code" => "BLR",
                "dial_code" => "+375",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Belgium",
                "slug" => "belgium",
                "code" => "BEL",
                "dial_code" => "+32",
                "flag" => "https://logos.football-data.org/805.svg",
                "continent" => "Europe",
            ],
            [
                "name" => "Belize",
                "slug" => "belize",
                "code" => "BLZ",
                "dial_code" => "+501",
                "flag" => null,
                "continent" => "N/C America",
            ],
            [
                "name" => "Benin",
                "slug" => "benin",
                "code" => "BEN",
                "dial_code" => "+229",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Bermuda",
                "slug" => "bermuda",
                "code" => "BMU",
                "dial_code" => "+1-441",
                "flag" => null,
                "continent" => "N/C America",
            ],
            [
                "name" => "Bhutan",
                "slug" => "bhutan",
                "code" => "BHU",
                "dial_code" => "+975",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Bolivia",
                "slug" => "bolivia",
                "code" => "BOL",
                "dial_code" => "+591",
                "flag" => null,
                "continent" => "South America",
            ],
            [
                "name" => "Bonaire",
                "slug" => "bonaire",
                "code" => "BON",
                "dial_code" => null,
                "flag" => null,
                "continent" => "N/C America",
            ],
            [
                "name" => "Bosnia and Herzegovina",
                "slug" => "bosnia-and-herzegovina",
                "code" => "BIH",
                "dial_code" => "+387",
                "flag" => "https://logos.football-data.org/bosnia.svg",
                "continent" => "Europe",
            ],
            [
                "name" => "Botswana",
                "slug" => "botswana",
                "code" => "BOT",
                "dial_code" => "+267",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Brazil",
                "slug" => "brazil",
                "code" => "BRA",
                "dial_code" => "+55",
                "flag" => "https://logos.football-data.org/764.svg",
                "continent" => "South America",
            ],
            [
                "name" => "British Virgin Islands",
                "slug" => "british-virgin-islands",
                "code" => "BVI",
                "dial_code" => null,
                "flag" => null,
                "continent" => "N/C America",
            ],
            [
                "name" => "Brunei Darussalam",
                "slug" => "brunei-darussalam",
                "code" => "BRU",
                "dial_code" => "+673",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Bulgaria",
                "slug" => "bulgaria",
                "code" => "BGR",
                "dial_code" => "+359",
                "flag" => "https://logos.football-data.org/817.svg",
                "continent" => "Europe",
            ],
            [
                "name" => "Burkina Faso",
                "slug" => "burkina-faso",
                "code" => "BFA",
                "dial_code" => "+226",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Burundi",
                "slug" => "burundi",
                "code" => "BDI",
                "dial_code" => "+257",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Cambodia",
                "slug" => "cambodia",
                "code" => "CAM",
                "dial_code" => "+855",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Cameroon",
                "slug" => "cameroon",
                "code" => "CMR",
                "dial_code" => "+237",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Canada",
                "slug" => "canada",
                "code" => "CAN",
                "dial_code" => "+1",
                "flag" => null,
                "continent" => "N/C America",
            ],
            [
                "name" => "Cape Verde Islands",
                "slug" => "cape-verde-islands",
                "code" => "CPV",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Cayman Islands",
                "slug" => "cayman-islands",
                "code" => "CYM",
                "dial_code" => "+1-345",
                "flag" => null,
                "continent" => "N/C America",
            ],
            [
                "name" => "Central African Republic",
                "slug" => "central-african-republic",
                "code" => "CTA",
                "dial_code" => "+236",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Chad",
                "slug" => "chad",
                "code" => "CHA",
                "dial_code" => "+235",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Chile",
                "slug" => "chile",
                "code" => "CHL",
                "dial_code" => "+56",
                "flag" => null,
                "continent" => "South America",
            ],
            [
                "name" => "China PR",
                "slug" => "china-pr",
                "code" => "CHN",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Chinese Taipei",
                "slug" => "chinese-taipei",
                "code" => "TPE",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "CIS",
                "slug" => "cis",
                "code" => "CIS",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Colombia",
                "slug" => "colombia",
                "code" => "COL",
                "dial_code" => "+57",
                "flag" => null,
                "continent" => "South America",
            ],
            [
                "name" => "Comoros",
                "slug" => "comoros",
                "code" => "CMO",
                "dial_code" => "+269",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Congo",
                "slug" => "congo",
                "code" => "CGO",
                "dial_code" => "+242",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Congo DR",
                "slug" => "congo-dr",
                "code" => "COD",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Cook Islands",
                "slug" => "cook-islands",
                "code" => "COK",
                "dial_code" => "+682",
                "flag" => null,
                "continent" => "Oceania",
            ],
            [
                "name" => "Corsica",
                "slug" => "corsica",
                "code" => "COR",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Costa Rica",
                "slug" => "costa-rica",
                "code" => "CRI",
                "dial_code" => "+506",
                "flag" => null,
                "continent" => "N/C America",
            ],
            [
                "name" => "Côte d’Ivoire",
                "slug" => "cote-divoire",
                "code" => "CIV",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Crimea",
                "slug" => "crimea",
                "code" => "ARC",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Croatia",
                "slug" => "croatia",
                "code" => "HRV",
                "dial_code" => "+385",
                "flag" => "https://logos.football-data.org/799.svg",
                "continent" => "Europe",
            ],
            [
                "name" => "Cuba",
                "slug" => "cuba",
                "code" => "CUB",
                "dial_code" => "+53",
                "flag" => null,
                "continent" => "N/C America",
            ],
            [
                "name" => "Curaçao",
                "slug" => "curacao",
                "code" => "ANT",
                "dial_code" => null,
                "flag" => null,
                "continent" => "N/C America",
            ],
            [
                "name" => "Cyprus",
                "slug" => "cyprus",
                "code" => "CYP",
                "dial_code" => "+357",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Czech Republic",
                "slug" => "czech-republic",
                "code" => "CZE",
                "dial_code" => "+420",
                "flag" => "https://logos.football-data.org/798.svg",
                "continent" => "Europe",
            ],
            [
                "name" => "Czechoslovakia",
                "slug" => "czechoslovakia",
                "code" => "CZS",
                "dial_code" => null,
                "flag" => "https://logos.football-data.org/798.svg",
                "continent" => "Europe",
            ],
            [
                "name" => "Darfur",
                "slug" => "darfur",
                "code" => "DAR",
                "dial_code" => null,
                "flag" => null,
                "continent" => "World",
            ],
            [
                "name" => "Denmark",
                "slug" => "denmark",
                "code" => "DNK",
                "dial_code" => "+45",
                "flag" => "https://logos.football-data.org/782.svg",
                "continent" => "Europe",
            ],
            [
                "name" => "Djibouti",
                "slug" => "djibouti",
                "code" => "DJI",
                "dial_code" => "+253",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Dominica",
                "slug" => "dominica",
                "code" => "DMA",
                "dial_code" => "+1-767",
                "flag" => null,
                "continent" => "N/C America",
            ],
            [
                "name" => "Dominican Republic",
                "slug" => "dominican-republic",
                "code" => "DOM",
                "dial_code" => "+1-809, +1-829, +1-849",
                "flag" => null,
                "continent" => "N/C America",
            ],
            [
                "name" => "Ecuador",
                "slug" => "ecuador",
                "code" => "ECU",
                "dial_code" => "+593",
                "flag" => null,
                "continent" => "South America",
            ],
            [
                "name" => "Egypt",
                "slug" => "egypt",
                "code" => "EGY",
                "dial_code" => "+20",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "El Salvador",
                "slug" => "el-salvador",
                "code" => "SLV",
                "dial_code" => "+503",
                "flag" => null,
                "continent" => "N/C America",
            ],
            [
                "name" => "England",
                "slug" => "england",
                "code" => "ENG",
                "dial_code" => "+44",
                "flag" => "https://logos.football-data.org/770.svg",
                "continent" => "Europe",
            ],
            [
                "name" => "Equatorial Guinea",
                "slug" => "equatorial-guinea",
                "code" => "EQG",
                "dial_code" => "+240",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Eritrea",
                "slug" => "eritrea",
                "code" => "ERI",
                "dial_code" => "+291",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Estonia",
                "slug" => "estonia",
                "code" => "EST",
                "dial_code" => "+372",
                "flag" => "https://logos.football-data.org/estonia.svg",
                "continent" => "Europe",
            ],
            [
                "name" => "Ethiopia",
                "slug" => "ethiopia",
                "code" => "ETH",
                "dial_code" => "+251",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Europe",
                "slug" => "europe",
                "code" => "EUR",
                "dial_code" => "+44",
                "flag" => "https://logos.football-data.org/EUR.svg",
                "continent" => "World",
            ],
            [
                "name" => "Faroe Islands",
                "slug" => "faroe-islands",
                "code" => "FRO",
                "dial_code" => "+298",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Fiji",
                "slug" => "fiji",
                "code" => "FJI",
                "dial_code" => "+679",
                "flag" => null,
                "continent" => "Oceania",
            ],
            [
                "name" => "Finland",
                "slug" => "finland",
                "code" => "FIN",
                "dial_code" => "+358",
                "flag" => "https://logos.football-data.org/1976.svg",
                "continent" => "Europe",
            ],
            [
                "name" => "France",
                "slug" => "france",
                "code" => "FRA",
                "dial_code" => "+33",
                "flag" => "https://logos.football-data.org/773.svg",
                "continent" => "Europe",
            ],
            [
                "name" => "French Guiana",
                "slug" => "french-guiana",
                "code" => "FGU",
                "dial_code" => "+594",
                "flag" => null,
                "continent" => "N/C America",
            ],
            [
                "name" => "FYR Macedonia",
                "slug" => "fyr-macedonia",
                "code" => "MKD",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Gabon",
                "slug" => "gabon",
                "code" => "GAB",
                "dial_code" => "+241",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Gambia",
                "slug" => "gambia",
                "code" => "GAM",
                "dial_code" => "+220",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "GDR",
                "slug" => "gdr",
                "code" => "GDR",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Georgia",
                "slug" => "georgia",
                "code" => "GEO",
                "dial_code" => "+995",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Germany",
                "slug" => "germany",
                "code" => "DEU",
                "dial_code" => "+49",
                "flag" => "https://logos.football-data.org/759.svg",
                "continent" => "Europe",
            ],
            [
                "name" => "Ghana",
                "slug" => "ghana",
                "code" => "GHA",
                "dial_code" => "+233",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Gibraltar",
                "slug" => "gibraltar",
                "code" => "GIB",
                "dial_code" => "+350",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Gozo",
                "slug" => "gozo",
                "code" => "GOZ",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Great Britain",
                "slug" => "great-britain",
                "code" => "GBR",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Greece",
                "slug" => "greece",
                "code" => "GRC",
                "dial_code" => "+30",
                "flag" => "https://logos.football-data.org/775.svg",
                "continent" => "Europe",
            ],
            [
                "name" => "Greenland",
                "slug" => "greenland",
                "code" => "GEE",
                "dial_code" => "+299",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Grenada",
                "slug" => "grenada",
                "code" => "GRD",
                "dial_code" => "+1-473",
                "flag" => null,
                "continent" => "N/C America",
            ],
            [
                "name" => "Guadeloupe",
                "slug" => "guadeloupe",
                "code" => "GDL",
                "dial_code" => "+590",
                "flag" => null,
                "continent" => "N/C America",
            ],
            [
                "name" => "Guam",
                "slug" => "guam",
                "code" => "GUM",
                "dial_code" => "+1-671",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Guatemala",
                "slug" => "guatemala",
                "code" => "GTM",
                "dial_code" => "+502",
                "flag" => null,
                "continent" => "N/C America",
            ],
            [
                "name" => "Guernsey",
                "slug" => "guernsey",
                "code" => "GGY",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Guinea",
                "slug" => "guinea",
                "code" => "GUI",
                "dial_code" => "+224",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Guinea-Bissau",
                "slug" => "guinea-bissau",
                "code" => "GNB",
                "dial_code" => "+245",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Guyana",
                "slug" => "guyana",
                "code" => "GUY",
                "dial_code" => "+592",
                "flag" => null,
                "continent" => "N/C America",
            ],
            [
                "name" => "Haiti",
                "slug" => "haiti",
                "code" => "HTI",
                "dial_code" => "+509",
                "flag" => null,
                "continent" => "N/C America",
            ],
            [
                "name" => "Honduras",
                "slug" => "honduras",
                "code" => "HND",
                "dial_code" => "+504",
                "flag" => null,
                "continent" => "N/C America",
            ],
            [
                "name" => "Hong Kong",
                "slug" => "hong-kong",
                "code" => "HKG",
                "dial_code" => "+852",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Hungary",
                "slug" => "hungary",
                "code" => "HUN",
                "dial_code" => "+36",
                "flag" => "https://logos.football-data.org/827.svg",
                "continent" => "Europe",
            ],
            [
                "name" => "Iceland",
                "slug" => "iceland",
                "code" => "ISL",
                "dial_code" => "+354",
                "flag" => "https://logos.football-data.org/iceland.svg",
                "continent" => "Europe",
            ],
            [
                "name" => "India",
                "slug" => "india",
                "code" => "IND",
                "dial_code" => "+91",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Indonesia",
                "slug" => "indonesia",
                "code" => "IDN",
                "dial_code" => "+62",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Iran",
                "slug" => "iran",
                "code" => "IRN",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Iraq",
                "slug" => "iraq",
                "code" => "IRQ",
                "dial_code" => "+964",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Isle of Man",
                "slug" => "isle-of-man",
                "code" => "IOM",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Israel",
                "slug" => "israel",
                "code" => "ISR",
                "dial_code" => "+972",
                "flag" => "https://logos.football-data.org/israel.svg",
                "continent" => "Europe",
            ],
            [
                "name" => "Italy",
                "slug" => "italy",
                "code" => "ITA",
                "dial_code" => "+39",
                "flag" => "https://logos.football-data.org/784.svg",
                "continent" => "Europe",
            ],
            [
                "name" => "Jamaica",
                "slug" => "jamaica",
                "code" => "JAM",
                "dial_code" => "+1-876",
                "flag" => null,
                "continent" => "N/C America",
            ],
            [
                "name" => "Japan",
                "slug" => "japan",
                "code" => "JPN",
                "dial_code" => "+81",
                "flag" => "https://logos.football-data.org/JAP.svg",
                "continent" => "Asia",
            ],
            [
                "name" => "Jersey",
                "slug" => "jersey",
                "code" => "JER",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Jordan",
                "slug" => "jordan",
                "code" => "JOR",
                "dial_code" => "+962",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Kazakhstan",
                "slug" => "kazakhstan",
                "code" => "KAZ",
                "dial_code" => "+7",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Kenya",
                "slug" => "kenya",
                "code" => "KEN",
                "dial_code" => "+254",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Kiribati",
                "slug" => "kiribati",
                "code" => "KIR",
                "dial_code" => "+686",
                "flag" => null,
                "continent" => "Oceania",
            ],
            [
                "name" => "Korea DPR",
                "slug" => "korea-dpr",
                "code" => "PRK",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Korea Republic",
                "slug" => "korea-republic",
                "code" => "KOR",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Kosovo",
                "slug" => "kosovo",
                "code" => "KSV",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Kurdistan",
                "slug" => "kurdistan",
                "code" => "KUR",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Kuwait",
                "slug" => "kuwait",
                "code" => "KUW",
                "dial_code" => "+965",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Kyrgyzstan",
                "slug" => "kyrgyzstan",
                "code" => "KGZ",
                "dial_code" => "+996",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Laos",
                "slug" => "laos",
                "code" => "LAO",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Latvia",
                "slug" => "latvia",
                "code" => "LVA",
                "dial_code" => "+371",
                "flag" => "https://logos.football-data.org/latvia.svg",
                "continent" => "Europe",
            ],
            [
                "name" => "Lebanon",
                "slug" => "lebanon",
                "code" => "LIB",
                "dial_code" => "+961",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Lesotho",
                "slug" => "lesotho",
                "code" => "LES",
                "dial_code" => "+266",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Liberia",
                "slug" => "liberia",
                "code" => "LBR",
                "dial_code" => "+231",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Libya",
                "slug" => "libya",
                "code" => "LBY",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Liechtenstein",
                "slug" => "liechtenstein",
                "code" => "LIE",
                "dial_code" => "+423",
                "flag" => "https://logos.football-data.org/1982.svg",
                "continent" => "Europe",
            ],
            [
                "name" => "Lithuania",
                "slug" => "lithuania",
                "code" => "LTU",
                "dial_code" => "+370",
                "flag" => "https://logos.football-data.org/1983.svg",
                "continent" => "Europe",
            ],
            [
                "name" => "Luxembourg",
                "slug" => "luxembourg",
                "code" => "LUX",
                "dial_code" => "+352",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Macao",
                "slug" => "macao",
                "code" => "MAC",
                "dial_code" => "+853",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Madagascar",
                "slug" => "madagascar",
                "code" => "MAD",
                "dial_code" => "+261",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Malawi",
                "slug" => "malawi",
                "code" => "MWI",
                "dial_code" => "+265",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Malaysia",
                "slug" => "malaysia",
                "code" => "MAS",
                "dial_code" => "+60",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Maldives",
                "slug" => "maldives",
                "code" => "MDV",
                "dial_code" => "+960",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Mali",
                "slug" => "mali",
                "code" => "MLI",
                "dial_code" => "+223",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Malta",
                "slug" => "malta",
                "code" => "MLT",
                "dial_code" => "+356",
                "flag" => "https://logos.football-data.org/malta.svg",
                "continent" => "Europe",
            ],
            [
                "name" => "Marshall Islands",
                "slug" => "marshall-islands",
                "code" => "MSI",
                "dial_code" => "+692",
                "flag" => null,
                "continent" => "Oceania",
            ],
            [
                "name" => "Martinique",
                "slug" => "martinique",
                "code" => "MTQ",
                "dial_code" => "+596",
                "flag" => null,
                "continent" => "N/C America",
            ],
            [
                "name" => "Mauritania",
                "slug" => "mauritania",
                "code" => "MTN",
                "dial_code" => "+222",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Mauritius",
                "slug" => "mauritius",
                "code" => "MRI",
                "dial_code" => "+230",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Mayotte",
                "slug" => "mayotte",
                "code" => "MYT",
                "dial_code" => "+262",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Mexico",
                "slug" => "mexico",
                "code" => "MEX",
                "dial_code" => "+52",
                "flag" => "https://logos.football-data.org/mexico.svg",
                "continent" => "N/C America",
            ],
            [
                "name" => "Micronesia",
                "slug" => "micronesia",
                "code" => "MIC",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Oceania",
            ],
            [
                "name" => "Moldova",
                "slug" => "moldova",
                "code" => "MHL",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Monaco",
                "slug" => "monaco",
                "code" => "MCO",
                "dial_code" => "+377",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Mongolia",
                "slug" => "mongolia",
                "code" => "MGL",
                "dial_code" => "+976",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Montenegro",
                "slug" => "montenegro",
                "code" => "MNE",
                "dial_code" => "+382",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Montserrat",
                "slug" => "montserrat",
                "code" => "MSR",
                "dial_code" => "+1-664",
                "flag" => null,
                "continent" => "N/C America",
            ],
            [
                "name" => "Morocco",
                "slug" => "morocco",
                "code" => "MAR",
                "dial_code" => "+212",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Mozambique",
                "slug" => "mozambique",
                "code" => "MOZ",
                "dial_code" => "+258",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Myanmar",
                "slug" => "myanmar",
                "code" => "MYA",
                "dial_code" => "+95",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "N/C America",
                "slug" => "nc-america",
                "code" => "NCA",
                "dial_code" => null,
                "flag" => null,
                "continent" => "World",
            ],
            [
                "name" => "Namibia",
                "slug" => "namibia",
                "code" => "NAM",
                "dial_code" => "+264",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Nauru",
                "slug" => "nauru",
                "code" => "NAU",
                "dial_code" => "+674",
                "flag" => null,
                "continent" => "Oceania",
            ],
            [
                "name" => "Nepal",
                "slug" => "nepal",
                "code" => "NEP",
                "dial_code" => "+977",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Netherlands",
                "slug" => "netherlands",
                "code" => "NLD",
                "dial_code" => "+31",
                "flag" => "https://logos.football-data.org/8601.svg",
                "continent" => "Europe",
            ],
            [
                "name" => "New Caledonia",
                "slug" => "new-caledonia",
                "code" => "NCL",
                "dial_code" => "+687",
                "flag" => null,
                "continent" => "Oceania",
            ],
            [
                "name" => "New Zealand",
                "slug" => "new-zealand",
                "code" => "NZL",
                "dial_code" => "+64",
                "flag" => null,
                "continent" => "Oceania",
            ],
            [
                "name" => "NF-Board",
                "slug" => "nf-board",
                "code" => "NFB",
                "dial_code" => null,
                "flag" => null,
                "continent" => "World",
            ],
            [
                "name" => "Nicaragua",
                "slug" => "nicaragua",
                "code" => "NIC",
                "dial_code" => "+505",
                "flag" => null,
                "continent" => "N/C America",
            ],
            [
                "name" => "Niger",
                "slug" => "niger",
                "code" => "NIG",
                "dial_code" => "+227",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Nigeria",
                "slug" => "nigeria",
                "code" => "NGA",
                "dial_code" => "+234",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Niue",
                "slug" => "niue",
                "code" => "NIU",
                "dial_code" => "+683",
                "flag" => null,
                "continent" => "Oceania",
            ],
            [
                "name" => "Northern Ireland",
                "slug" => "northern-ireland",
                "code" => "NIR",
                "dial_code" => "+44",
                "flag" => "https://logos.football-data.org/829.svg",
                "continent" => "Europe",
            ],
            [
                "name" => "Northern Mariana Islands",
                "slug" => "northern-mariana-islands",
                "code" => "NMI",
                "dial_code" => "+1-670",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Norway",
                "slug" => "norway",
                "code" => "NOR",
                "dial_code" => "+47",
                "flag" => "https://logos.football-data.org/813.svg",
                "continent" => "Europe",
            ],
            [
                "name" => "Occitania",
                "slug" => "occitania",
                "code" => "OCC",
                "dial_code" => null,
                "flag" => null,
                "continent" => "World",
            ],
            [
                "name" => "Oceania",
                "slug" => "oceania",
                "code" => "OCE",
                "dial_code" => null,
                "flag" => null,
                "continent" => "World",
            ],
            [
                "name" => "Oman",
                "slug" => "oman",
                "code" => "OMA",
                "dial_code" => "+968",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Padania",
                "slug" => "padania",
                "code" => "PAD",
                "dial_code" => null,
                "flag" => null,
                "continent" => "World",
            ],
            [
                "name" => "Pakistan",
                "slug" => "pakistan",
                "code" => "PAK",
                "dial_code" => "+92",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Palau",
                "slug" => "palau",
                "code" => "PLA",
                "dial_code" => "+680",
                "flag" => null,
                "continent" => "Oceania",
            ],
            [
                "name" => "Palestine",
                "slug" => "palestine",
                "code" => "PAL",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Panama",
                "slug" => "panama",
                "code" => "PAN",
                "dial_code" => "+507",
                "flag" => null,
                "continent" => "N/C America",
            ],
            [
                "name" => "Papua New Guinea",
                "slug" => "papua-new-guinea",
                "code" => "PNG",
                "dial_code" => "+675",
                "flag" => null,
                "continent" => "Oceania",
            ],
            [
                "name" => "Paraguay",
                "slug" => "paraguay",
                "code" => "PRY",
                "dial_code" => "+595",
                "flag" => null,
                "continent" => "South America",
            ],
            [
                "name" => "Peru",
                "slug" => "peru",
                "code" => "PER",
                "dial_code" => "+51",
                "flag" => null,
                "continent" => "South America",
            ],
            [
                "name" => "Philippines",
                "slug" => "philippines",
                "code" => "PHI",
                "dial_code" => "+63",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Poland",
                "slug" => "poland",
                "code" => "POL",
                "dial_code" => "+48",
                "flag" => "https://logos.football-data.org/794.svg",
                "continent" => "Europe",
            ],
            [
                "name" => "Portugal",
                "slug" => "portugal",
                "code" => "POR",
                "dial_code" => "+351",
                "flag" => "https://logos.football-data.org/765.svg",
                "continent" => "Europe",
            ],
            [
                "name" => "Provence",
                "slug" => "provence",
                "code" => "PRO",
                "dial_code" => null,
                "flag" => null,
                "continent" => "World",
            ],
            [
                "name" => "Puerto Rico",
                "slug" => "puerto-rico",
                "code" => "PRI",
                "dial_code" => "+1-787, +1-939",
                "flag" => null,
                "continent" => "N/C America",
            ],
            [
                "name" => "Qatar",
                "slug" => "qatar",
                "code" => "QAT",
                "dial_code" => "+974",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Raetia",
                "slug" => "raetia",
                "code" => "RAE",
                "dial_code" => null,
                "flag" => null,
                "continent" => "World",
            ],
            [
                "name" => "Republic of Ireland",
                "slug" => "republic-of-ireland",
                "code" => "IRL",
                "dial_code" => null,
                "flag" => "https://logos.football-data.org/806.svg",
                "continent" => "Europe",
            ],
            [
                "name" => "Reunion",
                "slug" => "reunion",
                "code" => "REU",
                "dial_code" => "+262",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Romania",
                "slug" => "romania",
                "code" => "ROU",
                "dial_code" => "+40",
                "flag" => "https://logos.football-data.org/811.svg",
                "continent" => "Europe",
            ],
            [
                "name" => "Russia",
                "slug" => "russia",
                "code" => "RUS",
                "dial_code" => "+7",
                "flag" => "https://logos.football-data.org/808.svg",
                "continent" => "Europe",
            ],
            [
                "name" => "Rwanda",
                "slug" => "rwanda",
                "code" => "RWA",
                "dial_code" => "+250",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Saint Martin",
                "slug" => "saint-martin",
                "code" => "SMT",
                "dial_code" => null,
                "flag" => null,
                "continent" => "N/C America",
            ],
            [
                "name" => "Saint Pierre and Miquelon",
                "slug" => "saint-pierre-and-miquelon",
                "code" => "SPM",
                "dial_code" => "+508",
                "flag" => null,
                "continent" => "N/C America",
            ],
            [
                "name" => "Samoa",
                "slug" => "samoa",
                "code" => "WSM",
                "dial_code" => "+685",
                "flag" => null,
                "continent" => "Oceania",
            ],
            [
                "name" => "San Marino",
                "slug" => "san-marino",
                "code" => "SMR",
                "dial_code" => "+378",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "São Tomé e Príncipe",
                "slug" => "sao-tome-e-principe",
                "code" => "STP",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Sápmi",
                "slug" => "sapmi",
                "code" => "SAP",
                "dial_code" => null,
                "flag" => null,
                "continent" => "World",
            ],
            [
                "name" => "Saudi Arabia",
                "slug" => "saudi-arabia",
                "code" => "KSA",
                "dial_code" => "+966",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Scotland",
                "slug" => "scotland",
                "code" => "SCO",
                "dial_code" => "+44",
                "flag" => "https://logos.football-data.org/814.svg",
                "continent" => "Europe",
            ],
            [
                "name" => "Senegal",
                "slug" => "senegal",
                "code" => "SEN",
                "dial_code" => "+221",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Serbia",
                "slug" => "serbia",
                "code" => "SER",
                "dial_code" => "+381",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Serbia and Montenegro",
                "slug" => "serbia-and-montenegro",
                "code" => "SCG",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Seychelles",
                "slug" => "seychelles",
                "code" => "SEY",
                "dial_code" => "+248",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Shetland",
                "slug" => "shetland",
                "code" => "SHE",
                "dial_code" => null,
                "flag" =>
                    "https://upload.wikimedia.org/wikipedia/commons/0/0a/Flag_of_Shetland.svg",
                "continent" => "Europe",
            ],
            [
                "name" => "Sierra Leone",
                "slug" => "sierra-leone",
                "code" => "SLE",
                "dial_code" => "+232",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Singapore",
                "slug" => "singapore",
                "code" => "SIN",
                "dial_code" => "+65",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Sint Eustatius",
                "slug" => "sint-eustatius",
                "code" => "SEU",
                "dial_code" => null,
                "flag" => null,
                "continent" => "N/C America",
            ],
            [
                "name" => "Sint Maarten",
                "slug" => "sint-maarten",
                "code" => "SMA",
                "dial_code" => null,
                "flag" => null,
                "continent" => "N/C America",
            ],
            [
                "name" => "Slovakia",
                "slug" => "slovakia",
                "code" => "SVK",
                "dial_code" => "+421",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Slovenia",
                "slug" => "slovenia",
                "code" => "SVN",
                "dial_code" => "+386",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Solomon Islands",
                "slug" => "solomon-islands",
                "code" => "SLB",
                "dial_code" => "+677",
                "flag" => null,
                "continent" => "Oceania",
            ],
            [
                "name" => "Somalia",
                "slug" => "somalia",
                "code" => "SOM",
                "dial_code" => "+252",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Somaliland",
                "slug" => "somaliland",
                "code" => "SOL",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "South Africa",
                "slug" => "south-africa",
                "code" => "RSA",
                "dial_code" => "+27",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "South America",
                "slug" => "south-america",
                "code" => "SAM",
                "dial_code" => null,
                "flag" => "https://logos.football-data.org/CLI.svg",
                "continent" => "World",
            ],
            [
                "name" => "South Sudan",
                "slug" => "south-sudan",
                "code" => "SSD",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Southern Cameroon",
                "slug" => "southern-cameroon",
                "code" => "SCM",
                "dial_code" => null,
                "flag" => null,
                "continent" => "World",
            ],
            [
                "name" => "Soviet Union",
                "slug" => "soviet-union",
                "code" => "SOV",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Spain",
                "slug" => "spain",
                "code" => "ESP",
                "dial_code" => "+34",
                "flag" => "https://logos.football-data.org/760.svg",
                "continent" => "Europe",
            ],
            [
                "name" => "Sri Lanka",
                "slug" => "sri-lanka",
                "code" => "SRI",
                "dial_code" => "+94",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "St. Helena",
                "slug" => "st-helena",
                "code" => "STH",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "St. Kitts and Nevis",
                "slug" => "st-kitts-and-nevis",
                "code" => "SKN",
                "dial_code" => null,
                "flag" => null,
                "continent" => "N/C America",
            ],
            [
                "name" => "St. Lucia",
                "slug" => "st-lucia",
                "code" => "STL",
                "dial_code" => null,
                "flag" => null,
                "continent" => "N/C America",
            ],
            [
                "name" => "St. Vincent and the Grenadines",
                "slug" => "st-vincent-and-the-grenadines",
                "code" => "SVG",
                "dial_code" => null,
                "flag" => null,
                "continent" => "N/C America",
            ],
            [
                "name" => "Sudan",
                "slug" => "sudan",
                "code" => "SUD",
                "dial_code" => "+249",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Suriname",
                "slug" => "suriname",
                "code" => "SUR",
                "dial_code" => "+597",
                "flag" => null,
                "continent" => "N/C America",
            ],
            [
                "name" => "Swaziland",
                "slug" => "swaziland",
                "code" => "SWZ",
                "dial_code" => "+268",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Sweden",
                "slug" => "sweden",
                "code" => "SWE",
                "dial_code" => "+46",
                "flag" => "https://logos.football-data.org/792.svg",
                "continent" => "Europe",
            ],
            [
                "name" => "Switzerland",
                "slug" => "switzerland",
                "code" => "CHE",
                "dial_code" => "+41",
                "flag" => "https://logos.football-data.org/788.svg",
                "continent" => "Europe",
            ],
            [
                "name" => "Syria",
                "slug" => "syria",
                "code" => "SYR",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Tahiti",
                "slug" => "tahiti",
                "code" => "TAH",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Oceania",
            ],
            [
                "name" => "Tajikistan",
                "slug" => "tajikistan",
                "code" => "TJK",
                "dial_code" => "+992",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Tamil Eelam",
                "slug" => "tamil-eelam",
                "code" => "TEL",
                "dial_code" => null,
                "flag" => null,
                "continent" => "World",
            ],
            [
                "name" => "Tanzania",
                "slug" => "tanzania",
                "code" => "TAN",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Thailand",
                "slug" => "thailand",
                "code" => "THA",
                "dial_code" => "+66",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Timor-Leste",
                "slug" => "timor-leste",
                "code" => "EAT",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Togo",
                "slug" => "togo",
                "code" => "TOG",
                "dial_code" => "+228",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Tonga",
                "slug" => "tonga",
                "code" => "TON",
                "dial_code" => "+676",
                "flag" => null,
                "continent" => "Oceania",
            ],
            [
                "name" => "TR Northern Cyprus",
                "slug" => "tr-northern-cyprus",
                "code" => "NCY",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Trinidad and Tobago",
                "slug" => "trinidad-and-tobago",
                "code" => "TTO",
                "dial_code" => "+1-868",
                "flag" => null,
                "continent" => "N/C America",
            ],
            [
                "name" => "Tunisia",
                "slug" => "tunisia",
                "code" => "TUN",
                "dial_code" => "+216",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Turkey",
                "slug" => "turkey",
                "code" => "TUR",
                "dial_code" => "+90",
                "flag" => "https://logos.football-data.org/803.svg",
                "continent" => "Europe",
            ],
            [
                "name" => "Turkmenistan",
                "slug" => "turkmenistan",
                "code" => "TKM",
                "dial_code" => "+993",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Turks and Caicos Islands",
                "slug" => "turks-and-caicos-islands",
                "code" => "TCA",
                "dial_code" => "+1-649",
                "flag" => null,
                "continent" => "N/C America",
            ],
            [
                "name" => "Tuvalu",
                "slug" => "tuvalu",
                "code" => "TVL",
                "dial_code" => "+688",
                "flag" => null,
                "continent" => "Oceania",
            ],
            [
                "name" => "Two Sicilies",
                "slug" => "two-sicilies",
                "code" => "TSI",
                "dial_code" => null,
                "flag" => null,
                "continent" => "World",
            ],
            [
                "name" => "Uganda",
                "slug" => "uganda",
                "code" => "UGA",
                "dial_code" => "+256",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Ukraine",
                "slug" => "ukraine",
                "code" => "UKR",
                "dial_code" => "+380",
                "flag" => "https://logos.football-data.org/790.svg",
                "continent" => "Europe",
            ],
            [
                "name" => "United Arab Emirates",
                "slug" => "united-arab-emirates",
                "code" => "UAE",
                "dial_code" => "+971",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "United Kingdom",
                "slug" => "united-kingdom",
                "code" => "UK",
                "dial_code" => "+44",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "United States",
                "slug" => "united-states",
                "code" => "USA",
                "dial_code" => "+1",
                "flag" => "https://logos.football-data.org/usa.svg",
                "continent" => "N/C America",
            ],
            [
                "name" => "Uruguay",
                "slug" => "uruguay",
                "code" => "URY",
                "dial_code" => "+598",
                "flag" => null,
                "continent" => "South America",
            ],
            [
                "name" => "US Virgin Islands",
                "slug" => "us-virgin-islands",
                "code" => "USV",
                "dial_code" => null,
                "flag" => null,
                "continent" => "N/C America",
            ],
            [
                "name" => "Uzbekistan",
                "slug" => "uzbekistan",
                "code" => "UZB",
                "dial_code" => "+998",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Vanuatu",
                "slug" => "vanuatu",
                "code" => "VUT",
                "dial_code" => "+678",
                "flag" => null,
                "continent" => "Oceania",
            ],
            [
                "name" => "Vatican City",
                "slug" => "vatican-city",
                "code" => "VAC",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Venezuela",
                "slug" => "venezuela",
                "code" => "VEN",
                "dial_code" => "+58",
                "flag" => null,
                "continent" => "South America",
            ],
            [
                "name" => "Vietnam",
                "slug" => "vietnam",
                "code" => "VIE",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Wales",
                "slug" => "wales",
                "code" => "WAL",
                "dial_code" => "+44",
                "flag" => "https://logos.football-data.org/833.svg",
                "continent" => "Europe",
            ],
            [
                "name" => "West Indies",
                "slug" => "west-indies",
                "code" => "WIN",
                "dial_code" => null,
                "flag" => null,
                "continent" => "World",
            ],
            [
                "name" => "Western Sahara",
                "slug" => "western-sahara",
                "code" => "WSR",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "World",
                "slug" => "world",
                "code" => "INT",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Yemen",
                "slug" => "yemen",
                "code" => "YEM",
                "dial_code" => "+967",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Yugoslavia",
                "slug" => "yugoslavia",
                "code" => "YUG",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Zambia",
                "slug" => "zambia",
                "code" => "ZAM",
                "dial_code" => "+260",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Zanzibar",
                "slug" => "zanzibar",
                "code" => "ZAN",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Zimbabwe",
                "slug" => "zimbabwe",
                "code" => "ZIM",
                "dial_code" => "+263",
                "flag" => null,
                "continent" => "Africa",
            ],
        ];
        
        foreach ($countries as $country) {

            if ($country['continent']) {

                $continent = Continent::updateOrCreate(
                    ['name' => $country['continent']],
                    [
                        'name' => $country['continent'],
                        'slug' => Str::slug($country['continent'])
                    ]
                );
            }

            Country::updateOrCreate(
                ['name' => $country['name']],
                [
                    'name' => $country['name'],
                    'slug' => Str::slug($country['name']),
                    'code' => $country['code'],
                    'dial_code' => $country['dial_code'],
                    'flag' => $country['flag'],
                    'continent_id' => $continent->id ?? 0,
                    'status_id' => Status::where('name', 'active')->first()->id ?? 0
                ]
            );
        }
    }
}
