version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "80:80"  # Mapping port 8080 on the host to port 80 in the container
    volumes:
      - ../:/app  # Mount the parent directory to /app in the container
    depends_on:
      - db  # Ensure the app service waits for the db service to start
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=matchoracle
      - DB_USERNAME=root
      - DB_PASSWORD=rootpassword

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: matchoracle
      MYSQL_USER: matchoracleuser
      MYSQL_PASSWORD: userpassword
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"  # Exposing MySQL on port 3307

volumes:
  db_data:

