<?php

namespace Database\Seeders\Countries;

use App\Models\Continent;
use App\Models\Country;
use App\Models\Status;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        // Country::truncate();
        // DB::statement('ALTER TABLE countries AUTO_INCREMENT = 1100;');

        $countries = [

            [
                "name" => "Afghanistan",
                "code" => "AF",
                "dial_code" => "+93",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Åland Islands",
                "code" => "AX",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Albania",
                "code" => "AL",
                "dial_code" => "+355",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Algeria",
                "code" => "DZ",
                "dial_code" => "+213",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "American Samoa",
                "code" => "AS",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Oceania",
            ],
            [
                "name" => "Andorra",
                "code" => "AD",
                "dial_code" => "+376",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Angola",
                "code" => "AO",
                "dial_code" => "+244",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Anguilla",
                "code" => "AI",
                "dial_code" => "+1-264",
                "flag" => null,
                "continent" => "North & Central America",
            ],
            [
                "name" => "Antarctica",
                "code" => "AQ",
                "dial_code" => null,
                "flag" => null,
                "continent" => "World",
            ],
            [
                "name" => "Antigua and Barbuda",
                "code" => "AG",
                "dial_code" => "+1-268",
                "flag" => null,
                "continent" => "North & Central America",
            ],
            [
                "name" => "Argentina",
                "code" => "AR",
                "dial_code" => "+54",
                "flag" => null,
                "continent" => "South America",
            ],
            [
                "name" => "Armenia",
                "code" => "AM",
                "dial_code" => "+374",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Aruba",
                "code" => "AW",
                "dial_code" => "+297",
                "flag" => null,
                "continent" => "North & Central America",
            ],
            [
                "name" => "Australia",
                "code" => "AU",
                "dial_code" => "+61",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Australia & Oceania",
                "code" => "AOC",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Oceania",
            ],
            [
                "name" => "Austria",
                "code" => "AT",
                "dial_code" => "+43",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Azerbaijan",
                "code" => "AZ",
                "dial_code" => "+994",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Bahamas",
                "code" => "BS",
                "dial_code" => "+1-242",
                "flag" => null,
                "continent" => "North & Central America",
            ],
            [
                "name" => "Bahrain",
                "code" => "BH",
                "dial_code" => "+973",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Bangladesh",
                "code" => "BD",
                "dial_code" => "+880",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Barbados",
                "code" => "BB",
                "dial_code" => "+1-246",
                "flag" => null,
                "continent" => "North & Central America",
            ],
            [
                "name" => "Belarus",
                "code" => "BY",
                "dial_code" => "+375",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Belgium",
                "code" => "BE",
                "dial_code" => "+32",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Belize",
                "code" => "BZ",
                "dial_code" => "+501",
                "flag" => null,
                "continent" => "North & Central America",
            ],
            [
                "name" => "Benin",
                "code" => "BJ",
                "dial_code" => "+229",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Bermuda",
                "code" => "BM",
                "dial_code" => "+1-441",
                "flag" => null,
                "continent" => "North & Central America",
            ],
            [
                "name" => "Bhutan",
                "code" => "BT",
                "dial_code" => "+975",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Bolivia",
                "code" => "BO",
                "dial_code" => "+591",
                "flag" => null,
                "continent" => "South America",
            ],
            [
                "name" => "Bosnia and Herzegovina",
                "code" => "BA",
                "dial_code" => "+387",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Botswana",
                "code" => "BW",
                "dial_code" => "+267",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Bouvet Island",
                "code" => "BV",
                "dial_code" => null,
                "flag" => null,
                "continent" => null,
            ],
            [
                "name" => "Brazil",
                "code" => "BR",
                "dial_code" => "+55",
                "flag" => null,
                "continent" => "South America",
            ],
            [
                "name" => "British Indian Ocean Territory",
                "code" => "IO",
                "dial_code" => null,
                "flag" => null,
                "continent" => null,
            ],
            [
                "name" => "Brunei Darussalam",
                "code" => "BN",
                "dial_code" => "+673",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Bulgaria",
                "code" => "BG",
                "dial_code" => "+359",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Burkina Faso",
                "code" => "BF",
                "dial_code" => "+226",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Burundi",
                "code" => "BI",
                "dial_code" => "+257",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Cambodia",
                "code" => "KH",
                "dial_code" => "+855",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Cameroon",
                "code" => "CM",
                "dial_code" => "+237",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Canada",
                "code" => "CA",
                "dial_code" => "+1",
                "flag" => null,
                "continent" => "North & Central America",
            ],
            [
                "name" => "Cape Verde",
                "code" => "CV",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Cayman Islands",
                "code" => "KY",
                "dial_code" => "+1-345",
                "flag" => null,
                "continent" => "North & Central America",
            ],
            [
                "name" => "Central African Republic",
                "code" => "CF",
                "dial_code" => "+236",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Chad",
                "code" => "TD",
                "dial_code" => "+235",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Chile",
                "code" => "CL",
                "dial_code" => "+56",
                "flag" => null,
                "continent" => "South America",
            ],
            [
                "name" => "China",
                "code" => "CN",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Christmas Island",
                "code" => "CX",
                "dial_code" => null,
                "flag" => null,
                "continent" => null,
            ],
            [
                "name" => "Cocos (Keeling) Islands",
                "code" => "CC",
                "dial_code" => null,
                "flag" => null,
                "continent" => null,
            ],
            [
                "name" => "Colombia",
                "code" => "CO",
                "dial_code" => "+57",
                "flag" => null,
                "continent" => "South America",
            ],
            [
                "name" => "Comoros",
                "code" => "KM",
                "dial_code" => "+269",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "DR Congo",
                "code" => "CG",
                "dial_code" => "+242",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Republic of the Congo",
                "code" => "CD",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Cook Islands",
                "code" => "CK",
                "dial_code" => "+682",
                "flag" => null,
                "continent" => "Oceania",
            ],
            [
                "name" => "Corsica",
                "slug" => "corsica",
                "code" => "COR",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Costa Rica",
                "code" => "CR",
                "dial_code" => "+506",
                "flag" => null,
                "continent" => "North & Central America",
            ],
            [
                "name" => "Crimea",
                "code" => "ARC",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Croatia",
                "code" => "HR",
                "dial_code" => "+385",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Cuba",
                "code" => "CU",
                "dial_code" => "+53",
                "flag" => null,
                "continent" => "North & Central America",
            ],
            [
                "name" => "Curaçao",
                "code" => "CW",
                "dial_code" => null,
                "flag" => null,
                "continent" => "North & Central America",
            ],
            [
                "name" => "Cyprus",
                "code" => "CY",
                "dial_code" => "+357",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Czech Republic",
                "code" => "CZ",
                "dial_code" => "+420",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Denmark",
                "code" => "DK",
                "dial_code" => "+45",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Djibouti",
                "code" => "DJ",
                "dial_code" => "+253",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Dominica",
                "code" => "DM",
                "dial_code" => "+1-767",
                "flag" => null,
                "continent" => "North & Central America",
            ],
            [
                "name" => "Dominican Republic",
                "code" => "DO",
                "dial_code" => "+1-809, +1-829, +1-849",
                "flag" => null,
                "continent" => "North & Central America",
            ],
            [
                "name" => "Ecuador",
                "code" => "EC",
                "dial_code" => "+593",
                "flag" => null,
                "continent" => "South America",
            ],
            [
                "name" => "Egypt",
                "code" => "EG",
                "dial_code" => "+20",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "El Salvador",
                "code" => "SV",
                "dial_code" => "+503",
                "flag" => null,
                "continent" => "North & Central America",
            ],
            [
                "name" => "England",
                "slug" => "england",
                "code" => "ENG",
                "dial_code" => "+44",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Equatorial Guinea",
                "code" => "GQ",
                "dial_code" => "+240",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Eritrea",
                "code" => "ER",
                "dial_code" => "+291",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Estonia",
                "code" => "EE",
                "dial_code" => "+372",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Ethiopia",
                "code" => "ET",
                "dial_code" => "+251",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Falkland Islands (Malvinas)",
                "code" => "FK",
                "dial_code" => null,
                "flag" => null,
                "continent" => null,
            ],
            [
                "name" => "Faroe Islands",
                "code" => "FO",
                "dial_code" => "+298",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Fiji",
                "code" => "FJ",
                "dial_code" => "+679",
                "flag" => null,
                "continent" => "Oceania",
            ],
            [
                "name" => "Finland",
                "code" => "FI",
                "dial_code" => "+358",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "France",
                "code" => "FR",
                "dial_code" => "+33",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "French Guiana",
                "code" => "GF",
                "dial_code" => "+594",
                "flag" => null,
                "continent" => "North & Central America",
            ],
            [
                "name" => "French Polynesia",
                "code" => "PF",
                "dial_code" => null,
                "flag" => null,
                "continent" => null,
            ],
            [
                "name" => "French Southern Territories",
                "code" => "TF",
                "dial_code" => null,
                "flag" => null,
                "continent" => null,
            ],
            [
                "name" => "Gabon",
                "code" => "GA",
                "dial_code" => "+241",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Gambia",
                "code" => "GM",
                "dial_code" => "+220",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Georgia",
                "code" => "GE",
                "dial_code" => "+995",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Germany",
                "code" => "DE",
                "dial_code" => "+49",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Ghana",
                "code" => "GH",
                "dial_code" => "+233",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Gibraltar",
                "code" => "GI",
                "dial_code" => "+350",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Gozo",
                "code" => "GOZ",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Great Britain",
                "code" => "GB",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Greece",
                "code" => "GR",
                "dial_code" => "+30",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Greenland",
                "code" => "GL",
                "dial_code" => "+299",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Grenada",
                "code" => "GD",
                "dial_code" => "+1-473",
                "flag" => null,
                "continent" => "North & Central America",
            ],
            [
                "name" => "Guadeloupe",
                "code" => "GP",
                "dial_code" => "+590",
                "flag" => null,
                "continent" => "North & Central America",
            ],
            [
                "name" => "Guam",
                "code" => "GU",
                "dial_code" => "+1-671",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Guatemala",
                "code" => "GT",
                "dial_code" => "+502",
                "flag" => null,
                "continent" => "North & Central America",
            ],
            [
                "name" => "Guernsey",
                "code" => "GG",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Guinea",
                "code" => "GN",
                "dial_code" => "+224",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Guinea-Bissau",
                "code" => "GW",
                "dial_code" => "+245",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Guyana",
                "code" => "GY",
                "dial_code" => "+592",
                "flag" => null,
                "continent" => "North & Central America",
            ],
            [
                "name" => "Haiti",
                "code" => "HT",
                "dial_code" => "+509",
                "flag" => null,
                "continent" => "North & Central America",
            ],
            [
                "name" => "Heard Island and Mcdonald Islands",
                "code" => "HM",
                "dial_code" => null,
                "flag" => null,
                "continent" => null,
            ],
            [
                "name" => "Holy See (Vatican City State)",
                "code" => "VA",
                "dial_code" => null,
                "flag" => null,
                "continent" => null,
            ],
            [
                "name" => "Honduras",
                "code" => "HN",
                "dial_code" => "+504",
                "flag" => null,
                "continent" => "North & Central America",
            ],
            [
                "name" => "Hong Kong",
                "code" => "HK",
                "dial_code" => "+852",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Hungary",
                "code" => "HU",
                "dial_code" => "+36",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Iceland",
                "code" => "IS",
                "dial_code" => "+354",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "India",
                "code" => "IN",
                "dial_code" => "+91",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Indonesia",
                "code" => "ID",
                "dial_code" => "+62",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Iran",
                "code" => "IR",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Iraq",
                "code" => "IQ",
                "dial_code" => "+964",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Ireland",
                "code" => "IE",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Isle of Man",
                "code" => "IM",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Israel",
                "code" => "IL",
                "dial_code" => "+972",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Italy",
                "code" => "IT",
                "dial_code" => "+39",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Ivory Coast",
                "code" => "CI",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Jamaica",
                "code" => "JM",
                "dial_code" => "+1-876",
                "flag" => null,
                "continent" => "North & Central America",
            ],
            [
                "name" => "Japan",
                "code" => "JP",
                "dial_code" => "+81",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Jersey",
                "code" => "JE",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Jordan",
                "code" => "JO",
                "dial_code" => "+962",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Kazakhstan",
                "code" => "KZ",
                "dial_code" => "+7",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Kenya",
                "code" => "KE",
                "dial_code" => "+254",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Kiribati",
                "code" => "KI",
                "dial_code" => "+686",
                "flag" => null,
                "continent" => "Oceania",
            ],
            [
                "name" => "Kosovo",
                "code" => "XK",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Korea DPR",
                "code" => "KP",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "South Korea",
                "code" => "KR",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Kuwait",
                "code" => "KW",
                "dial_code" => "+965",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Kyrgyzstan",
                "code" => "KG",
                "dial_code" => "+996",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Lao People'S Democratic Republic",
                "code" => "LA",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Latvia",
                "code" => "LV",
                "dial_code" => "+371",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Lebanon",
                "code" => "LB",
                "dial_code" => "+961",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Lesotho",
                "code" => "LS",
                "dial_code" => "+266",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Liberia",
                "code" => "LR",
                "dial_code" => "+231",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Libya",
                "code" => "LY",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Liechtenstein",
                "code" => "LI",
                "dial_code" => "+423",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Lithuania",
                "code" => "LT",
                "dial_code" => "+370",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Luxembourg",
                "code" => "LU",
                "dial_code" => "+352",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Macau",
                "code" => "MO",
                "dial_code" => "+853",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "North Macedonia",
                "code" => "MK",
                "dial_code" => null,
                "flag" => null,
                "continent" => null,
            ],
            [
                "name" => "Madagascar",
                "code" => "MG",
                "dial_code" => "+261",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Malawi",
                "code" => "MW",
                "dial_code" => "+265",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Malaysia",
                "code" => "MY",
                "dial_code" => "+60",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Maldives",
                "code" => "MV",
                "dial_code" => "+960",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Mali",
                "code" => "ML",
                "dial_code" => "+223",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Malta",
                "code" => "MT",
                "dial_code" => "+356",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Marshall Islands",
                "code" => "MH",
                "dial_code" => "+692",
                "flag" => null,
                "continent" => "Oceania",
            ],
            [
                "name" => "Martinique",
                "code" => "MQ",
                "dial_code" => "+596",
                "flag" => null,
                "continent" => "North & Central America",
            ],
            [
                "name" => "Mauritania",
                "code" => "MR",
                "dial_code" => "+222",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Mauritius",
                "code" => "MU",
                "dial_code" => "+230",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Mayotte",
                "code" => "YT",
                "dial_code" => "+262",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Mexico",
                "code" => "MX",
                "dial_code" => "+52",
                "flag" => null,
                "continent" => "North & Central America",
            ],
            [
                "name" => "Micronesia, Federated States of",
                "code" => "FM",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Oceania",
            ],
            [
                "name" => "Moldova",
                "code" => "MD",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Monaco",
                "code" => "MC",
                "dial_code" => "+377",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Mongolia",
                "code" => "MN",
                "dial_code" => "+976",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Montenegro",
                "code" => "CS",
                "dial_code" => "+382",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Montserrat",
                "code" => "MS",
                "dial_code" => "+1-664",
                "flag" => null,
                "continent" => "North & Central America",
            ],
            [
                "name" => "Morocco",
                "code" => "MA",
                "dial_code" => "+212",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Mozambique",
                "code" => "MZ",
                "dial_code" => "+258",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Myanmar",
                "code" => "MM",
                "dial_code" => "+95",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Namibia",
                "code" => "NA",
                "dial_code" => "+264",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Nauru",
                "code" => "NR",
                "dial_code" => "+674",
                "flag" => null,
                "continent" => "Oceania",
            ],
            [
                "name" => "Nepal",
                "code" => "NP",
                "dial_code" => "+977",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Netherlands",
                "code" => "NL",
                "dial_code" => "+31",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Netherlands Antilles",
                "code" => "AN",
                "dial_code" => null,
                "flag" => null,
                "continent" => null,
            ],
            [
                "name" => "New Caledonia",
                "code" => "NC",
                "dial_code" => "+687",
                "flag" => null,
                "continent" => "Oceania",
            ],
            [
                "name" => "New Zealand",
                "code" => "NZ",
                "dial_code" => "+64",
                "flag" => null,
                "continent" => "Oceania",
            ],
            [
                "name" => "Nicaragua",
                "code" => "NI",
                "dial_code" => "+505",
                "flag" => null,
                "continent" => "North & Central America",
            ],
            [
                "name" => "Niger",
                "code" => "NE",
                "dial_code" => "+227",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Nigeria",
                "code" => "NG",
                "dial_code" => "+234",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Niue",
                "code" => "NU",
                "dial_code" => "+683",
                "flag" => null,
                "continent" => "Oceania",
            ],
            [
                "name" => "Norfolk Island",
                "code" => "NF",
                "dial_code" => null,
                "flag" => null,
                "continent" => null,
            ],
            [
                "name" => "Northern Ireland",
                "code" => "NIR",
                "dial_code" => "+44",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Northern Mariana Islands",
                "code" => "MP",
                "dial_code" => "+1-670",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Norway",
                "code" => "NO",
                "dial_code" => "+47",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Oman",
                "code" => "OM",
                "dial_code" => "+968",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Pakistan",
                "code" => "PAK",
                "dial_code" => "+92",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Palau",
                "code" => "PW",
                "dial_code" => "+680",
                "flag" => null,
                "continent" => "Oceania",
            ],
            [
                "name" => "Palestine",
                "code" => "PAL",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Asia",
            ],

            [
                "name" => "Panama",
                "code" => "PA",
                "dial_code" => "+507",
                "flag" => null,
                "continent" => "North & Central America",
            ],
            [
                "name" => "Papua New Guinea",
                "code" => "PG",
                "dial_code" => "+675",
                "flag" => null,
                "continent" => "Oceania",
            ],
            [
                "name" => "Paraguay",
                "code" => "PY",
                "dial_code" => "+595",
                "flag" => null,
                "continent" => "South America",
            ],
            [
                "name" => "Peru",
                "code" => "PE",
                "dial_code" => "+51",
                "flag" => null,
                "continent" => "South America",
            ],
            [
                "name" => "Philippines",
                "code" => "PH",
                "dial_code" => "+63",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Pitcairn",
                "code" => "PN",
                "dial_code" => null,
                "flag" => null,
                "continent" => null,
            ],
            [
                "name" => "Poland",
                "code" => "PL",
                "dial_code" => "+48",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Portugal",
                "code" => "PT",
                "dial_code" => "+351",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Puerto Rico",
                "code" => "PR",
                "dial_code" => "+1-787, +1-939",
                "flag" => null,
                "continent" => "North & Central America",
            ],
            [
                "name" => "Qatar",
                "code" => "QA",
                "dial_code" => "+974",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Reunion",
                "code" => "RE",
                "dial_code" => "+262",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Romania",
                "code" => "RO",
                "dial_code" => "+40",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Russia",
                "code" => "RUS",
                "dial_code" => "+7",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "RWANDA",
                "code" => "RW",
                "dial_code" => "+250",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Saint Helena",
                "code" => "SH",
                "dial_code" => null,
                "flag" => null,
                "continent" => null,
            ],
            [
                "name" => "Saint Kitts and Nevis",
                "code" => "KN",
                "dial_code" => null,
                "flag" => null,
                "continent" => null,
            ],
            [
                "name" => "Saint Lucia",
                "code" => "LC",
                "dial_code" => null,
                "flag" => null,
                "continent" => null,
            ],
            [
                "name" => "Saint Pierre and Miquelon",
                "code" => "PM",
                "dial_code" => "+508",
                "flag" => null,
                "continent" => "North & Central America",
            ],
            [
                "name" => "Saint Vincent and the Grenadines",
                "code" => "VC",
                "dial_code" => null,
                "flag" => null,
                "continent" => null,
            ],
            [
                "name" => "Samoa",
                "code" => "WS",
                "dial_code" => "+685",
                "flag" => null,
                "continent" => "Oceania",
            ],
            [
                "name" => "San Marino",
                "code" => "SM",
                "dial_code" => "+378",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Sao Tome and Principe",
                "code" => "ST",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Saudi Arabia",
                "code" => "SA",
                "dial_code" => "+966",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Scotland",
                "slug" => "scotland",
                "code" => "SCO",
                "dial_code" => "+44",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Senegal",
                "code" => "SN",
                "dial_code" => "+221",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Serbia",
                "code" => "SER",
                "dial_code" => "+381",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Seychelles",
                "code" => "SC",
                "dial_code" => "+248",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Sierra Leone",
                "code" => "SL",
                "dial_code" => "+232",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Singapore",
                "code" => "SG",
                "dial_code" => "+65",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Slovakia",
                "code" => "SK",
                "dial_code" => "+421",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Slovenia",
                "code" => "SI",
                "dial_code" => null,
                "flag" => null,
                "continent" => null,
            ],
            [
                "name" => "Solomon Islands",
                "code" => "SB",
                "dial_code" => null,
                "flag" => null,
                "continent" => null,
            ],
            [
                "name" => "Somalia",
                "code" => "SO",
                "dial_code" => "+252",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "South Africa",
                "code" => "ZA",
                "dial_code" => "+27",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "South Georgia and the South Sandwich Islands",
                "code" => "GS",
                "dial_code" => null,
                "flag" => null,
                "continent" => null,
            ],
            [
                "name" => "Spain",
                "code" => "ES",
                "dial_code" => "+34",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Sri Lanka",
                "code" => "LK",
                "dial_code" => "+94",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Sudan",
                "code" => "SD",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Suriname",
                "code" => "SR",
                "dial_code" => null,
                "flag" => null,
                "continent" => null,
            ],
            [
                "name" => "Svalbard and Jan Mayen",
                "code" => "SJ",
                "dial_code" => null,
                "flag" => null,
                "continent" => null,
            ],
            [
                "name" => "Swaziland",
                "code" => "SZ",
                "dial_code" => "+268",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Sweden",
                "code" => "SE",
                "dial_code" => "+46",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Switzerland",
                "code" => "CH",
                "dial_code" => "+41",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Syria",
                "code" => "SY",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Taiwan",
                "code" => "TW",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Tajikistan",
                "code" => "TJ",
                "dial_code" => "+992",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Tanzania",
                "code" => "TZ",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Thailand",
                "code" => "TH",
                "dial_code" => "+66",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Timor-Leste",
                "code" => "TL",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Togo",
                "code" => "TG",
                "dial_code" => "+228",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Tokelau",
                "code" => "TK",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Oceania",
            ],
            [
                "name" => "Tonga",
                "code" => "TO",
                "dial_code" => "+676",
                "flag" => null,
                "continent" => "Oceania",
            ],
            [
                "name" => "Trinidad and Tobago",
                "code" => "TT",
                "dial_code" => "+1-868",
                "flag" => null,
                "continent" => "North & Central America",
            ],
            [
                "name" => "Tunisia",
                "code" => "TN",
                "dial_code" => "+216",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Turkey",
                "code" => "TR",
                "dial_code" => "+90",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Turkmenistan",
                "code" => "TM",
                "dial_code" => "+993",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Turks and Caicos Islands",
                "code" => "TC",
                "dial_code" => "+1-649",
                "flag" => null,
                "continent" => "North & Central America",
            ],
            [
                "name" => "Tuvalu",
                "code" => "TV",
                "dial_code" => "+688",
                "flag" => null,
                "continent" => "Oceania",
            ],
            [
                "name" => "Uganda",
                "code" => "UG",
                "dial_code" => "+256",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Ukraine",
                "code" => "UA",
                "dial_code" => "+380",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "United Arab Emirates",
                "code" => "AE",
                "dial_code" => "+971",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "United Kingdom",
                "code" => "GB",
                "dial_code" => "+44",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "United States",
                "code" => "US",
                "dial_code" => "+1",
                "flag" => null,
                "continent" => "North & Central America",
            ],
            [
                "name" => "Uruguay",
                "code" => "UY",
                "dial_code" => "+598",
                "flag" => null,
                "continent" => "South America",
            ],
            [
                "name" => "Uzbekistan",
                "code" => "UZ",
                "dial_code" => "+998",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Vanuatu",
                "code" => "VU",
                "dial_code" => null,
                "flag" => null,
                "continent" => null,
            ],
            [
                "name" => "Venezuela",
                "code" => "VE",
                "dial_code" => "+58",
                "flag" => null,
                "continent" => "South America",
            ],
            [
                "name" => "Vietnam",
                "code" => "VN",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Virgin Islands, British",
                "code" => "VG",
                "dial_code" => null,
                "flag" => null,
                "continent" => "North & Central America",
            ],
            [
                "name" => "Virgin Islands, U.S.",
                "code" => "VI",
                "dial_code" => null,
                "flag" => null,
                "continent" => null,
            ],
            [
                "name" => "Wales",
                "code" => "WAL",
                "dial_code" => "+44",
                "flag" => null,
                "continent" => "Europe",
            ],
            [
                "name" => "Wallis and Futuna",
                "code" => "WF",
                "dial_code" => null,
                "flag" => null,
                "continent" => null,
            ],
            [
                "name" => "Western Sahara",
                "code" => "EH",
                "dial_code" => null,
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Yemen",
                "code" => "YE",
                "dial_code" => "+967",
                "flag" => null,
                "continent" => "Asia",
            ],
            [
                "name" => "Zambia",
                "code" => "ZM",
                "dial_code" => "+260",
                "flag" => null,
                "continent" => "Africa",
            ],
            [
                "name" => "Zimbabwe",
                "code" => "ZW",
                "dial_code" => "+263",
                "flag" => null,
                "continent" => "Africa",
            ],

            [
                "name" => "Africa",
                "code" => "AFR",
                "dial_code" => null,
                "flag" => null,
                "continent" => "World",
            ],
            [
                "name" => "Arameans Suryoye",
                "code" => "ARS",
                "dial_code" => null,
                "flag" => null,
                "continent" => "World",
            ],
            [
                "name" => "Asia",
                "slug" => "asia",
                "code" => "ASI",
                "dial_code" => null,
                "flag" => null,
                "continent" => "World",
            ],
            [
                "name" => "Darfur",
                "code" => "DAR",
                "dial_code" => null,
                "flag" => null,
                "continent" => "World",
            ],
            [
                "name" => "Europe",
                "code" => "EU",
                "dial_code" => "+44",
                "flag" => null,
                "continent" => "World",
            ],
            [
                "name" => "North & Central America",
                "code" => "NAC",
                "dial_code" => null,
                "flag" => null,
                "continent" => "World",
            ],
            [
                "name" => "Occitania",
                "code" => "OCC",
                "dial_code" => null,
                "flag" => null,
                "continent" => "World",
            ],
            [
                "name" => "Oceania",
                "code" => "OCE",
                "dial_code" => null,
                "flag" => null,
                "continent" => "World",
            ],
            [
                "name" => "Padania",
                "code" => "PAD",
                "dial_code" => null,
                "flag" => null,
                "continent" => "World",
            ],
            [
                "name" => "Provence",
                "code" => "PRO",
                "dial_code" => null,
                "flag" => null,
                "continent" => "World",
            ],
            [
                "name" => "Raetia",
                "code" => "RAE",
                "dial_code" => null,
                "flag" => null,
                "continent" => "World",
            ],
            [
                "name" => "South America",
                "code" => "SAM",
                "dial_code" => null,
                "flag" => null,
                "continent" => "World",
            ],
            [
                "name" => "Southern Cameroon",
                "code" => "SCM",
                "dial_code" => null,
                "flag" => null,
                "continent" => "World",
            ],
            [
                "name" => "Tamil Eelam",
                "code" => "TEL",
                "dial_code" => null,
                "flag" => null,
                "continent" => "World",
            ],
            [
                "name" => "Two Sicilies",
                "code" => "TSI",
                "dial_code" => null,
                "flag" => null,
                "continent" => "World",
            ],
            [
                "name" => "West Indies",
                "code" => "WIN",
                "dial_code" => null,
                "flag" => null,
                "continent" => "World",
            ],
            [
                "name" => "World",
                "code" => "INT",
                "dial_code" => null,
                "flag" => null,
                "continent" => "World",
            ],
        ];

        // dd(count($countries))
        foreach ($countries as $country) {

            if ($country['continent']) {

                $continent = Continent::updateOrCreate(
                    [
                        'name' => $country['continent']
                    ],
                    [
                        'name' => $country['continent'],
                        'slug' => Str::slug($country['continent']),
                        'status_id' => activeStatusId()
                    ]
                );
            }

            $is_international = $country['name'] == $country['continent'];

            Country::updateOrCreate(
                ['name' => $country['name']],
                [
                    'name' => $country['name'],
                    'slug' => Str::slug($country['name']),
                    'code' => $country['code'],
                    'dial_code' => $country['dial_code'],
                    'flag' => 'assets/images/flags/png100px/' . Str::slug($country['code']) . '.png',
                    'is_international' => $is_international,
                    'continent_id' => $continent->id ?? 0,
                    'status_id' => activeStatusId()
                ]
            );
        }
    }
}
