services:
  react-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3080:3080"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    command: node server.js
