<?php

namespace App\Services\GameSources\Forebet;

use App\Models\GameSource;

class BaseHandlerController

{
    public $url;
    public $config;
    public $sourceUrl;
    public $reqPrefs = array();
    public $sourceId;

    public function __construct()
    {
        $this->config['sourceUrl'] = 'https://www.forebet.com/';

        $this->sourceUrl = $this->config['sourceUrl'];

        $this->reqPrefs['http']['method'] = 'GET';

        $this->sourceId = GameSource::updateOrCreate([
            'url' => $this->sourceUrl,
        ], [
            'name' => 'Mathematical football predictions /forebets/ and football statistics',
            'url' => $this->sourceUrl,
            'description' => 'Forebet presents mathematical football predictions generated by computer algorithm on the basis of statistics. Predictions, statistics, live-score, match previews and detailed analysis for more than 700 football leagues',
            'priority_number' => 2,
            'status_id' => activeStatusId(),
            'user_id' => auth()->id() ?? 0,
        ])->id ?? 0;
    }
}
