import App from "@/utils/App"
import { NavLink } from "react-router-dom"

type Props = {}

const Index = (props: Props) => {


  return (
    <div>
      <div className="page-container">
        <div className="main-content">
          <div className="doc-index-page-title-wrapper">
            <h1 className="page-title">{App.name()} 1.1 Documentation</h1>
            <div className="container-fluid row">
              <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat minima vero doloribus. Sit quasi quisquam perspiciatis asperiores, commodi tempora dolorem voluptates, dolor vel impedit iure est blanditiis. Illum vel laboriosam quaerat tempore excepturi, modi optio explicabo adipisci, blanditiis consequuntur aperiam maiores tempora dolorem quidem ducimus sed suscipit dignissimos! Corrupti soluta eaque ducimus voluptatum recusandae itaque quaerat voluptas? Assumenda officiis vitae repellat ad facilis, magni harum nisi in voluptatem adipisci possimus exercitationem sequi, repudiandae id dolores temporibus molestias sapiente natus rerum minus sit porro iste dolorum odio. Quisquam nulla labore sunt dolorum. Officiis asperiores quos aperiam dolorem illum consequuntur sint magni impedit maiores. Veniam explicabo fugiat unde? Consequatur harum architecto unde totam, eaque voluptas ut consectetur perspiciatis dolor vel amet quo corrupti quidem quae blanditiis numquam quisquam hic? Iusto nam saepe qui quod reiciendis dolorem accusantium sint, molestias consequuntur ipsum impedit veritatis, sit, tenetur amet numquam eaque. Quas consectetur non atque. Doloremque aspernatur sapiente dolorem praesentium consequatur sequi quos enim labore error exercitationem minus at impedit dignissimos quae, recusandae eos, quidem perspiciatis in inventore ullam corporis officiis cupiditate doloribus. Quibusdam aut illo laboriosam veritatis eos sapiente at non architecto nisi ratione cupiditate laborum voluptates perspiciatis, impedit tenetur officiis inventore ducimus harum! Est unde veritatis minima, ducimus cupiditate sequi recusandae voluptas eaque error repudiandae facilis, accusamus rerum commodi? Repellat, commodi obcaecati ullam perferendis delectus excepturi non est necessitatibus corporis dolorum. Amet facere natus nobis saepe laboriosam, voluptas ea laudantium optio quisquam dignissimos iste animi magnam doloribus aspernatur itaque sequi ullam quod nam eligendi earum quaerat qui culpa. Error voluptatem saepe ullam minus, autem aperiam quos deleniti doloremque, ipsa nesciunt voluptas nam voluptatibus ducimus, tenetur id suscipit eius aliquam possimus at aliquid commodi iure debitis? Minus numquam, amet cum pariatur repudiandae tenetur harum doloribus sint in magnam molestias ex magni adipisci, dolores accusantium.
              </p>
              <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat minima vero doloribus. Sit quasi quisquam perspiciatis asperiores, commodi tempora dolorem voluptates, dolor vel impedit iure est blanditiis. Illum vel laboriosam quaerat tempore excepturi, modi optio explicabo adipisci, blanditiis consequuntur aperiam maiores tempora dolorem quidem ducimus sed suscipit dignissimos! Corrupti soluta eaque ducimus voluptatum recusandae itaque quaerat voluptas? Assumenda officiis vitae repellat ad facilis, magni harum nisi in voluptatem adipisci possimus exercitationem sequi, repudiandae id dolores temporibus molestias sapiente natus rerum minus sit porro iste dolorum odio. Quisquam nulla labore sunt dolorum. Officiis asperiores quos aperiam dolorem illum consequuntur sint magni impedit maiores. Veniam explicabo fugiat unde? Consequatur harum architecto unde totam, eaque voluptas ut consectetur perspiciatis dolor vel amet quo corrupti quidem quae blanditiis numquam quisquam hic? Iusto nam saepe qui quod reiciendis dolorem accusantium sint, molestias consequuntur ipsum impedit veritatis, sit, tenetur amet numquam eaque. Quas consectetur non atque. Doloremque aspernatur sapiente dolorem praesentium consequatur sequi quos enim labore error exercitationem minus at impedit dignissimos quae, recusandae eos, quidem perspiciatis in inventore ullam corporis officiis cupiditate doloribus. Quibusdam aut illo laboriosam veritatis eos sapiente at non architecto nisi ratione cupiditate laborum voluptates perspiciatis, impedit tenetur officiis inventore ducimus harum! Est unde veritatis minima, ducimus cupiditate sequi recusandae voluptas eaque error repudiandae facilis, accusamus rerum commodi? Repellat, commodi obcaecati ullam perferendis delectus excepturi non est necessitatibus corporis dolorum. Amet facere natus nobis saepe laboriosam, voluptas ea laudantium optio quisquam dignissimos iste animi magnam doloribus aspernatur itaque sequi ullam quod nam eligendi earum quaerat qui culpa. Error voluptatem saepe ullam minus, autem aperiam quos deleniti doloremque, ipsa nesciunt voluptas nam voluptatibus ducimus, tenetur id suscipit eius aliquam possimus at aliquid commodi iure debitis? Minus numquam, amet cum pariatur repudiandae tenetur harum doloribus sint in magnam molestias ex magni adipisci, dolores accusantium.
              </p>
              <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat minima vero doloribus. Sit quasi quisquam perspiciatis asperiores, commodi tempora dolorem voluptates, dolor vel impedit iure est blanditiis. Illum vel laboriosam quaerat tempore excepturi, modi optio explicabo adipisci, blanditiis consequuntur aperiam maiores tempora dolorem quidem ducimus sed suscipit dignissimos! Corrupti soluta eaque ducimus voluptatum recusandae itaque quaerat voluptas? Assumenda officiis vitae repellat ad facilis, magni harum nisi in voluptatem adipisci possimus exercitationem sequi, repudiandae id dolores temporibus molestias sapiente natus rerum minus sit porro iste dolorum odio. Quisquam nulla labore sunt dolorum. Officiis asperiores quos aperiam dolorem illum consequuntur sint magni impedit maiores. Veniam explicabo fugiat unde? Consequatur harum architecto unde totam, eaque voluptas ut consectetur perspiciatis dolor vel amet quo corrupti quidem quae blanditiis numquam quisquam hic? Iusto nam saepe qui quod reiciendis dolorem accusantium sint, molestias consequuntur ipsum impedit veritatis, sit, tenetur amet numquam eaque. Quas consectetur non atque. Doloremque aspernatur sapiente dolorem praesentium consequatur sequi quos enim labore error exercitationem minus at impedit dignissimos quae, recusandae eos, quidem perspiciatis in inventore ullam corporis officiis cupiditate doloribus. Quibusdam aut illo laboriosam veritatis eos sapiente at non architecto nisi ratione cupiditate laborum voluptates perspiciatis, impedit tenetur officiis inventore ducimus harum! Est unde veritatis minima, ducimus cupiditate sequi recusandae voluptas eaque error repudiandae facilis, accusamus rerum commodi? Repellat, commodi obcaecati ullam perferendis delectus excepturi non est necessitatibus corporis dolorum. Amet facere natus nobis saepe laboriosam, voluptas ea laudantium optio quisquam dignissimos iste animi magnam doloribus aspernatur itaque sequi ullam quod nam eligendi earum quaerat qui culpa. Error voluptatem saepe ullam minus, autem aperiam quos deleniti doloremque, ipsa nesciunt voluptas nam voluptatibus ducimus, tenetur id suscipit eius aliquam possimus at aliquid commodi iure debitis? Minus numquam, amet cum pariatur repudiandae tenetur harum doloribus sint in magnam molestias ex magni adipisci, dolores accusantium.
              </p>
              <p>
               Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat minima vero doloribus. Sit quasi quisquam perspiciatis asperiores, commodi tempora dolorem voluptates, dolor vel impedit iure est blanditiis. Illum vel laboriosam quaerat tempore excepturi, modi optio explicabo adipisci, blanditiis consequuntur aperiam maiores tempora dolorem quidem ducimus sed suscipit dignissimos! Corrupti soluta eaque ducimus voluptatum recusandae itaque quaerat voluptas? Assumenda officiis vitae repellat ad facilis, magni harum nisi in voluptatem adipisci possimus exercitationem sequi, repudiandae id dolores temporibus molestias sapiente natus rerum minus sit porro iste dolorum odio. Quisquam nulla labore sunt dolorum. Officiis asperiores quos aperiam dolorem illum consequuntur sint magni impedit maiores. Veniam explicabo fugiat unde? Consequatur harum architecto unde totam, eaque voluptas ut consectetur perspiciatis dolor vel amet quo corrupti quidem quae blanditiis numquam quisquam hic? Iusto nam saepe qui quod reiciendis dolorem accusantium sint, molestias consequuntur ipsum impedit veritatis, sit, tenetur amet numquam eaque. Quas consectetur non atque. Doloremque aspernatur sapiente dolorem praesentium consequatur sequi quos enim labore error exercitationem minus at impedit dignissimos quae, recusandae eos, quidem perspiciatis in inventore ullam corporis officiis cupiditate doloribus. Quibusdam aut illo laboriosam veritatis eos sapiente at non architecto nisi ratione cupiditate laborum voluptates perspiciatis, impedit tenetur officiis inventore ducimus harum! Est unde veritatis minima, ducimus cupiditate sequi recusandae voluptas eaque error repudiandae facilis, accusamus rerum commodi? Repellat, commodi obcaecati ullam perferendis delectus excepturi non est necessitatibus corporis dolorum. Amet facere natus nobis saepe laboriosam, voluptas ea laudantium optio quisquam dignissimos iste animi magnam doloribus aspernatur itaque sequi ullam quod nam eligendi earum quaerat qui culpa. Error voluptatem saepe ullam minus, autem aperiam quos deleniti doloremque, ipsa nesciunt voluptas nam voluptatibus ducimus, tenetur id suscipit eius aliquam possimus at aliquid commodi iure debitis? Minus numquam, amet cum pariatur repudiandae tenetur harum doloribus sint in magnam molestias ex magni adipisci, dolores accusantium.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default Index